/* ACTION TYPES */
export const GET_FRIENDS = 'GET_FRIENDS'
export const ADD_FRIEND = 'ADD_FRIEND'
export const DELETE_FRIEND = 'DELETE_FRIEND'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR'
