/* ACTION TYPES */
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR'
export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const DELETE_FRIEND = 'DELETE_FRIEND'
export const GET_FRIENDS = 'GET_FRIENDS'
export const INVALID_EMAIL = 'INVALID_EMAIL'
export const INVITE_FRIEND = 'INVITE_FRIEND'
